server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: users-service
            uri: http://todomaker-service:8082
            predicates:
              - Path=/users/**

          - id: notes-service
            uri: http://todomaker-service:8082
            predicates:
              - Path=/notes/**

          - id: todos-service
            uri: http://todomaker-service:8082
            predicates:
              - Path=/todos/**
